version: "2"
services:
  db:
    image: postgres:9.5 
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:800"
    depends_on:
      - db
    volumes:
      - /home/ec2-user/www/:/webApps

